databases:
  - name: airbnbclone
    databaseName: airbnbnew
    user: airbnbclone
    region: singapore

services:
  - type: web
    name: airbnbnews
    env: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
